[package]
name = "coldmod-msg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "23.1.21"
prost = "0.11.9"
tonic = "0.9.2"
futures-util = "0.3.28"
tokio = { version = "1.28.0", features = ["full"] }

[build-dependencies]
tonic-build = "0.9.2"

[[example]]
name = "client"
