# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coldmod-msg/proto/heat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63oldmod-msg/proto/heat.proto\x12\x18\x63oldmod_msg.proto.source\x1a\x1bgoogle/protobuf/empty.proto\"R\n\x07HeatMap\x12\x11\n\troot_path\x18\x01 \x01(\t\x12\x34\n\theat_srcs\x18\x02 \x03(\x0b\x32!.coldmod_msg.proto.source.HeatSrc\"[\n\x07HeatSrc\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x17\n\nclass_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_class_name\"\"\n\x0fHeatMapRegister\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x01 \x01(\x08\x32\xa2\x01\n\x08HeatMaps\x12Q\n\x0c\x61vailability\x12\x16.google.protobuf.Empty\x1a).coldmod_msg.proto.source.HeatMapRegister\x12\x43\n\x06submit\x12!.coldmod_msg.proto.source.HeatMap\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coldmod_msg.proto.heat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HEATMAP']._serialized_start=87
  _globals['_HEATMAP']._serialized_end=169
  _globals['_HEATSRC']._serialized_start=171
  _globals['_HEATSRC']._serialized_end=262
  _globals['_HEATMAPREGISTER']._serialized_start=264
  _globals['_HEATMAPREGISTER']._serialized_end=298
  _globals['_HEATMAPS']._serialized_start=301
  _globals['_HEATMAPS']._serialized_end=463
# @@protoc_insertion_point(module_scope)
