# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from coldmod_msg.proto import heat_pb2 as coldmod__msg_dot_proto_dot_heat__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class HeatMapsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.availability = channel.unary_unary(
                '/coldmod_msg.proto.source.HeatMaps/availability',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=coldmod__msg_dot_proto_dot_heat__pb2.HeatMapRegister.FromString,
                )
        self.submit = channel.unary_unary(
                '/coldmod_msg.proto.source.HeatMaps/submit',
                request_serializer=coldmod__msg_dot_proto_dot_heat__pb2.HeatMap.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class HeatMapsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def availability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeatMapsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'availability': grpc.unary_unary_rpc_method_handler(
                    servicer.availability,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=coldmod__msg_dot_proto_dot_heat__pb2.HeatMapRegister.SerializeToString,
            ),
            'submit': grpc.unary_unary_rpc_method_handler(
                    servicer.submit,
                    request_deserializer=coldmod__msg_dot_proto_dot_heat__pb2.HeatMap.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coldmod_msg.proto.source.HeatMaps', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HeatMaps(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def availability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coldmod_msg.proto.source.HeatMaps/availability',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            coldmod__msg_dot_proto_dot_heat__pb2.HeatMapRegister.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coldmod_msg.proto.source.HeatMaps/submit',
            coldmod__msg_dot_proto_dot_heat__pb2.HeatMap.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
