# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coldmod-msg/proto/source.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63oldmod-msg/proto/source.proto\x12\x18\x63oldmod_msg.proto.source\x1a\x1bgoogle/protobuf/empty.proto\"p\n\nSourceScan\x12 \n\x18\x63oldmod_root_marker_path\x18\x01 \x01(\t\x12@\n\x0fsource_elements\x18\x02 \x03(\x0b\x32\'.coldmod_msg.proto.source.SourceElement\"I\n\rSourceElement\x12\x30\n\x02\x66n\x18\x01 \x01(\x0b\x32\".coldmod_msg.proto.source.SourceFnH\x00\x42\x06\n\x04\x65lem\"\\\n\x08SourceFn\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x17\n\nclass_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_class_name2V\n\x0cSourceDaemon\x12\x46\n\x06submit\x12$.coldmod_msg.proto.source.SourceScan\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coldmod_msg.proto.source_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOURCESCAN._serialized_start=89
  _SOURCESCAN._serialized_end=201
  _SOURCEELEMENT._serialized_start=203
  _SOURCEELEMENT._serialized_end=276
  _SOURCEFN._serialized_start=278
  _SOURCEFN._serialized_end=370
  _SOURCEDAEMON._serialized_start=372
  _SOURCEDAEMON._serialized_end=458
# @@protoc_insertion_point(module_scope)
