# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coldmod-msg/proto/trace.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63oldmod-msg/proto/trace.proto\x12\x17\x63oldmod_msg.proto.trace\x1a\x1bgoogle/protobuf/empty.proto\">\n\x05Trace\x12\x0e\n\x06\x64igest\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\x04\x12\x12\n\nprocess_id\x18\x03 \x01(\x04\x32M\n\x06Traces\x12\x43\n\x07\x63ollect\x12\x1e.coldmod_msg.proto.trace.Trace\x1a\x16.google.protobuf.Empty(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coldmod_msg.proto.trace_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TRACE']._serialized_start=87
  _globals['_TRACE']._serialized_end=149
  _globals['_TRACES']._serialized_start=151
  _globals['_TRACES']._serialized_end=228
# @@protoc_insertion_point(module_scope)
